"""内嵌页面模板。

EdgeOne 云函数构建器只打包 .py，templates/*.html 可能丢失导致 TemplateNotFound，
故用 DictLoader 从本字典加载模板。
"""

TEMPLATES = {
    'index.html': '<!DOCTYPE html>\n<html lang="zh-CN">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">\n<title>剧本杀一站式平台</title>\n<link rel="stylesheet" href="/static/css/app.css">\n</head>\n<body>\n<div class="app">\n  <div class="topbar">\n    <h1><span class="logo">🎭 拼本社</span></h1>\n    <span class="badge" id="ai-badge">AI 加载中…</span>\n  </div>\n\n  <div class="hero">\n    <h2>拼本 · 找店 · 测本<br>角色陪伴，一站搞定</h2>\n    <p>把散落在各处的剧本杀需求，整合成一个入口</p>\n  </div>\n\n  <div class="wrap">\n    <div class="sec-title">选择你的身份</div>\n\n    <div class="entry" onclick="location.href=\'/player\'">\n      <div class="em">🕵️</div>\n      <div>\n        <h3>我是玩家</h3>\n        <p>测本 · 拼车组局 · 找店找本 · 角色陪伴</p>\n      </div>\n      <div class="arrow">›</div>\n    </div>\n\n    <div class="entry" onclick="location.href=\'/merchant\'">\n      <div class="em">🏪</div>\n      <div>\n        <h3>我是店家</h3>\n        <p>排期管理 · 剧本库 · DM 派单 · 经营看板</p>\n      </div>\n      <div class="arrow">›</div>\n    </div>\n\n    <div class="entry" onclick="location.href=\'/dm\'">\n      <div class="em">🎙️</div>\n      <div>\n        <h3>我是 DM</h3>\n        <p>接单市场 · 我的场次 · 个人主页</p>\n      </div>\n      <div class="arrow">›</div>\n    </div>\n\n    <div class="divider"></div>\n    <p class="muted" style="font-size:12px;text-align:center">\n      北极星·炼术师 出品 · 剧本杀垂直社交平台 Demo\n    </p>\n  </div>\n</div>\n<script>\nfetch(\'/api/system/info\').then(r=>r.json()).then(d=>{\n  const b=document.getElementById(\'ai-badge\');\n  if(d.llm_ready){b.textContent=\'AI · \'+d.model;b.className=\'badge on\';}\n  else{b.textContent=\'AI 降级模式\';}\n});\n</script>\n</body>\n</html>\n',
    'player.html': '<!DOCTYPE html>\n<html lang="zh-CN">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">\n<title>拼本社 · 玩家端</title>\n<link rel="stylesheet" href="/static/css/app.css">\n</head>\n<body>\n<div class="app">\n  <div class="topbar">\n    <h1><span class="logo">🎭 拼本社</span></h1>\n    <span class="badge" id="ai-badge">AI…</span>\n  </div>\n  <div id="view"></div>\n  <div class="tabbar">\n    <a data-v="home" onclick="go(\'home\')" class="active"><span class="ic">🏠</span>首页</a>\n    <a data-v="test" onclick="go(\'test\')"><span class="ic">🔮</span>测本</a>\n    <a data-v="plaza" onclick="go(\'plaza\')"><span class="ic">🚗</span>拼车</a>\n    <a data-v="roles" onclick="go(\'roles\')"><span class="ic">💬</span>陪伴</a>\n    <a data-v="mine" onclick="go(\'mine\')"><span class="ic">👤</span>我的</a>\n  </div>\n</div>\n<script src="/static/js/common.js"></script>\n<script src="/static/js/player.js"></script>\n</body>\n</html>\n',
    'merchant.html': '<!DOCTYPE html>\n<html lang="zh-CN">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">\n<title>拼本社 · 店家端</title>\n<link rel="stylesheet" href="/static/css/app.css">\n</head>\n<body>\n<div class="app">\n  <div class="topbar">\n    <h1><span class="logo">🏪 店家端</span> <span class="muted" style="font-size:12px">解忧剧本社</span></h1>\n    <span class="badge" id="ai-badge">AI…</span>\n  </div>\n  <div id="view"></div>\n  <div class="tabbar">\n    <a data-v="dash" onclick="go(\'dash\')" class="active"><span class="ic">📊</span>看板</a>\n    <a data-v="schedule" onclick="go(\'schedule\')"><span class="ic">📅</span>排期</a>\n    <a data-v="scripts" onclick="go(\'scripts\')"><span class="ic">📚</span>剧本库</a>\n    <a data-v="dms" onclick="go(\'dms\')"><span class="ic">🎙️</span>DM</a>\n  </div>\n</div>\n<script src="/static/js/common.js"></script>\n<script src="/static/js/merchant.js"></script>\n</body>\n</html>\n',
    'dm.html': '<!DOCTYPE html>\n<html lang="zh-CN">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">\n<title>拼本社 · DM端</title>\n<link rel="stylesheet" href="/static/css/app.css">\n</head>\n<body>\n<div class="app">\n  <div class="topbar">\n    <h1><span class="logo">🎙️ DM 端</span></h1>\n    <span class="badge" id="ai-badge">AI…</span>\n  </div>\n  <div id="view"></div>\n  <div class="tabbar">\n    <a data-v="orders" onclick="go(\'orders\')" class="active"><span class="ic">🎬</span>我的场次</a>\n    <a data-v="market" onclick="go(\'market\')"><span class="ic">📢</span>接单市场</a>\n    <a data-v="profile" onclick="go(\'profile\')"><span class="ic">👤</span>主页</a>\n  </div>\n</div>\n<script src="/static/js/common.js"></script>\n<script src="/static/js/dm.js"></script>\n</body>\n</html>\n',
}
